/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 8.0.15 : Database - base_config
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`base_config` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */;

USE `base_config`;

/*Table structure for table `config_info` */

DROP TABLE IF EXISTS `config_info`;

CREATE TABLE `config_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_configinfo_datagrouptenant` (`data_id`,`group_id`,`tenant_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=137 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='config_info';

/*Data for the table `config_info` */

insert  into `config_info`(`id`,`data_id`,`group_id`,`content`,`md5`,`gmt_create`,`gmt_modified`,`src_user`,`src_ip`,`app_name`,`tenant_id`,`c_desc`,`c_use`,`effect`,`type`,`c_schema`) values 
(1,'dynamic_routes','DEFAULT_GROUP','routes:\r\n# base-auth\r\n- id: base-auth\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /auth/**\r\n  filters:\r\n  - name: ValidateCodeGatewayFilter\r\n    args: {}\r\n  - name: PasswordDecoderFilter\r\n    args: {}\r\n  uri: lb://base-auth\r\n  order: 0\r\n# base-upms-admin\r\n- id: base-upms-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /admin/**\r\n  filters:\r\n  - name: RequestRateLimiter\r\n    args: \r\n      # 限流策略\r\n      key-resolver: \'#{@remoteAddrKeyResolver}\'\r\n      # 令牌桶每秒填充率\r\n      redis-rate-limiter.burstCapacity: 20\r\n      # 令牌桶容量\r\n      redis-rate-limiter.replenishRate: 10\r\n  # 熔断\r\n  - name: Hystrix\r\n    args: \r\n      fallbackUri: \'forward:/fallback\'\r\n      name: default\r\n  uri: lb://base-upms-admin\r\n  order: 0\r\n# base-codegen\r\n- id: base-codegen\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /gen/**\r\n  filters: []\r\n  uri: lb://base-codegen\r\n  order: 0\r\n# base-weixin-admin\r\n- id: base-weixin-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /weixin/**\r\n  filters: []\r\n  uri: lb://base-weixin-admin\r\n  order: 0\r\n# base-mall-admin\r\n- id: base-mall-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /mall/**\r\n  filters: []\r\n  uri: lb://base-mall-admin\r\n  order: 0','329faf07128e6e0a984d5ce275ebfe39','2019-07-30 14:26:08','2019-09-03 12:51:07',NULL,'192.168.1.115','','','动态路由配置','null','null','yaml','null'),
(2,'application-dev.yml','DEFAULT_GROUP','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    host: ${REDIS-HOST:base-redis}\n    port: 6379\n    password: \n    database: 0\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','1b2aca659e88a8873547e3bb7aaabc5e','2019-07-28 23:14:26','2019-09-24 17:05:59',NULL,'192.168.1.115','','','主配置文件','null','null','yaml','null'),
(3,'base-gateway-dev.yml','DEFAULT_GROUP','security:\n  encode:\n    # 前端密码密钥，必须16位\n    key: \'1234567891234567\'\n\n# 不校验验证码终端\nignore:\n  clients:\n    - swagger\n  swagger-providers:\n    - ${AUTH-HOST:base-auth}','951580823377e19ddbae79a4276ff678','2019-07-28 23:14:26','2019-07-30 14:29:24',NULL,'192.168.1.117','','','网关配置','null','null','yaml','null'),
(4,'base-auth-dev.yml','DEFAULT_GROUP','# 数据源\nspring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    druid:\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      username: ${MYSQL-USER:root}\n      password: ${MYSQL-PWD:root}\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_upms}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\n  freemarker:\n    allow-request-override: false\n    allow-session-override: false\n    cache: true\n    charset: UTF-8\n    check-template-location: true\n    content-type: text/html\n    enabled: true\n    expose-request-attributes: false\n    expose-session-attributes: false\n    expose-spring-macro-helpers: true\n    prefer-file-system-access: true\n    suffix: .ftl\n    template-loader-path: classpath:/templates/','f8f481e11e51d1afc0cbc86d78c1a78a','2019-07-28 23:14:26','2019-08-21 17:51:41',NULL,'192.168.1.117','','','认证授权配置','null','null','yaml','null'),
(5,'base-upms-admin-dev.yml','DEFAULT_GROUP','## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      client-id: admin\n      client-secret: admin\n      scope: server\n      # 无需token访问的url\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n        - /user/register\n\n# 数据源\nspring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    druid:\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      username: ${MYSQL-USER:root}\n      password: ${MYSQL-PWD:root}\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_upms}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\n\n# Logger Config sql日志\nlogging:\n  level:\n    com.joolun.cloud.upms.admin.mapper: debug\n\nbase:\n  # 租户表维护\n  tenant:\n    column: tenant_id\n    tables:\n      - sys_user\n      - sys_role\n      - sys_organ\n      - sys_log\n  #数据权限配置\n  datascope:\n    mapperIds:\n      - com.joolun.cloud.upms.admin.mapper.SysUserMapper.getUserVosPage\n        \n#邮箱配置\nemail:\n  mailSmtpHost: smtpdm.aliyun.com\n  mailSmtpUsername: 你的邮箱\n  mailSmtpPassword: 邮箱密码\n  siteName: JooLun科技','8b490e968f4e65ab797fc4b7e5838900','2019-07-28 23:14:26','2019-08-22 21:46:53',NULL,'192.168.31.203','','','用户权限管理配置','null','null','yaml','null'),
(6,'base-codegen-dev.yml','DEFAULT_GROUP','## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      client-id: gen\n      client-secret: gen\n      scope: server\n# 数据源配置\nspring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    druid:\n      driver-class-name: com.mysql.cj.jdbc.Driver\n      username: ${MYSQL-USER:root}\n      password: ${MYSQL-PWD:root}\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_upms}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\n  resources:\n    static-locations: classpath:/static/,classpath:/views/\n\n\nbase:\n  tenant:\n    column: tenant_id\n    tables:\n      - sys_datasource','b86ba529d8e534057301a8c8bd3566ea','2019-07-28 23:14:26','2019-08-21 17:52:29',NULL,'192.168.1.117','','','代码生成配置','null','null','yaml','null'),
(7,'base-weixin-admin-dev.yml','DEFAULT_GROUP','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /portal/**\r\n        - /ws/**\r\n        - /open/notify/**\r\n        - /open/auth/**\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_wx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.weixin.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - wx_app\r\n      - wx_menu\r\n      - wx_user\r\n      - wx_auto_reply\r\n      - wx_msg\r\n      - wx_mass_msg\r\n  #数据权限配置\r\n  datascope:\r\n    mapperIds:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.selectPage\r\n\r\n# 微信第三方平台配置，请自行申请\r\nwx:\r\n  component:\r\n    appId: 请自行申请\r\n    appSecret: 请自行申请\r\n    token: 请自行申请\r\n    aesKey: 请自行申请','3524fb8d297368d7469ef967bee18da2','2019-07-28 23:14:26','2019-09-27 16:02:29',NULL,'192.168.1.115','','','微信公众号配置','null','null','yaml','null'),
(8,'base-mall-admin-dev.yml','DEFAULT_GROUP','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n      - user_collect\r\n      - goods_appraises\r\n  #商城相关配置\r\n  mall:\r\n    #支付、物流回调地址域名\r\n    notify-host: http://test.joolun.com\r\n    #快递100授权key\r\n    logistics-key: 你的快递100授权key','10b62ca39c3d9c6c7cd0ee433911f7b3','2019-08-12 12:03:16','2019-09-27 16:01:46',NULL,'192.168.1.115','','','商城管理配置','null','null','yaml','null');

/*Table structure for table `config_info_aggr` */

DROP TABLE IF EXISTS `config_info_aggr`;

CREATE TABLE `config_info_aggr` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_configinfoaggr_datagrouptenantdatum` (`data_id`,`group_id`,`tenant_id`,`datum_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='增加租户字段';

/*Data for the table `config_info_aggr` */

/*Table structure for table `config_info_beta` */

DROP TABLE IF EXISTS `config_info_beta`;

CREATE TABLE `config_info_beta` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_configinfobeta_datagrouptenant` (`data_id`,`group_id`,`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='config_info_beta';

/*Data for the table `config_info_beta` */

/*Table structure for table `config_info_tag` */

DROP TABLE IF EXISTS `config_info_tag`;

CREATE TABLE `config_info_tag` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_configinfotag_datagrouptenanttag` (`data_id`,`group_id`,`tenant_id`,`tag_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='config_info_tag';

/*Data for the table `config_info_tag` */

/*Table structure for table `config_tags_relation` */

DROP TABLE IF EXISTS `config_tags_relation`;

CREATE TABLE `config_tags_relation` (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE KEY `uk_configtagrelation_configidtag` (`id`,`tag_name`,`tag_type`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='config_tag_relation';

/*Data for the table `config_tags_relation` */

/*Table structure for table `group_capacity` */

DROP TABLE IF EXISTS `group_capacity`;

CREATE TABLE `group_capacity` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '配额，0表示使用默认值',
  `usage` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '使用量',
  `max_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_group_id` (`group_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='集群、各Group容量信息表';

/*Data for the table `group_capacity` */

/*Table structure for table `his_config_info` */

DROP TABLE IF EXISTS `his_config_info`;

CREATE TABLE `his_config_info` (
  `id` bigint(64) unsigned NOT NULL,
  `nid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin,
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  KEY `idx_gmt_create` (`gmt_create`) USING BTREE,
  KEY `idx_gmt_modified` (`gmt_modified`) USING BTREE,
  KEY `idx_did` (`data_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=138 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='多租户改造';

/*Data for the table `his_config_info` */

insert  into `his_config_info`(`id`,`nid`,`data_id`,`group_id`,`app_name`,`content`,`md5`,`gmt_create`,`gmt_modified`,`src_user`,`src_ip`,`op_type`,`tenant_id`) values 
(88,103,'base-weixin-ma-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: miniapp\r\n      client-secret: miniapp\r\n      scope: server\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_wx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.weixin.ma.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - wx_app\r\n      - wx_menu\r\n      - wx_user\r\n      - wx_auto_reply\r\n      - wx_msg\r\n      - wx_mass_msg\r\n    # 不需要租户信息约束的sql\r\n    ignoreMss:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.findByWeixinSign\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.findByAppId\r\n  #数据权限配置\r\n  datascope:\r\n    mapperIds:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.selectPage','b18f164966273a257e953ef6d4e4c8f8','2010-05-05 00:00:00','2019-08-30 17:36:49',NULL,'192.168.1.115','U',''),
(88,104,'base-weixin-ma-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: miniapp\r\n      client-secret: miniapp\r\n      scope: server\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_wx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.weixin.ma.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - wx_app\r\n      - wx_user\r\n  #数据权限配置\r\n  datascope:\r\n    mapperIds:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.selectPage','79e2723877c90b762f9907c42810199b','2010-05-05 00:00:00','2019-08-30 17:38:39',NULL,'192.168.1.115','U',''),
(2,105,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','a3a49794095c761844dbf51a284980c2','2010-05-05 00:00:00','2019-08-31 22:51:07',NULL,'192.168.31.203','U',''),
(2,106,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: true\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','44fe2991392cc4a44c7ca8e4a0305521','2010-05-05 00:00:00','2019-08-31 22:56:48',NULL,'192.168.31.203','U',''),
(2,107,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','a3a49794095c761844dbf51a284980c2','2010-05-05 00:00:00','2019-09-01 15:53:57',NULL,'192.168.31.203','U',''),
(2,108,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: true\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','44fe2991392cc4a44c7ca8e4a0305521','2010-05-05 00:00:00','2019-09-01 16:35:54',NULL,'192.168.31.203','U',''),
(1,109,'dynamic_routes','DEFAULT_GROUP','','routes:\r\n# base-auth\r\n- id: base-auth\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /auth/**\r\n  filters:\r\n  - name: ValidateCodeGatewayFilter\r\n    args: {}\r\n  - name: PasswordDecoderFilter\r\n    args: {}\r\n  uri: lb://base-auth\r\n  order: 0\r\n# base-upms-admin\r\n- id: base-upms-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /admin/**\r\n  filters:\r\n  - name: RequestRateLimiter\r\n    args: \r\n      # 限流策略\r\n      key-resolver: \'#{@remoteAddrKeyResolver}\'\r\n      # 令牌桶每秒填充率\r\n      redis-rate-limiter.burstCapacity: 20\r\n      # 令牌桶容量\r\n      redis-rate-limiter.replenishRate: 10\r\n  # 熔断\r\n  - name: Hystrix\r\n    args: \r\n      fallbackUri: \'forward:/fallback\'\r\n      name: default\r\n  uri: lb://base-upms-admin\r\n  order: 0\r\n# base-codegen\r\n- id: base-codegen\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /gen/**\r\n  filters: []\r\n  uri: lb://base-codegen\r\n  order: 0\r\n# base-weixin-mp\r\n- id: base-weixin-mp\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /wxmp/**\r\n  filters: []\r\n  uri: lb://base-weixin-mp\r\n  order: 0\r\n# base-weixin-ma\r\n- id: base-weixin-ma\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /wxma/**\r\n  filters: []\r\n  uri: lb://base-weixin-ma\r\n  order: 0\r\n# base-mall-admin\r\n- id: base-mall-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /mall/**\r\n  filters: []\r\n  uri: lb://base-mall-admin\r\n  order: 0','0f95288603c7ce8c9812440d871cf5f1','2010-05-05 00:00:00','2019-09-03 11:33:04',NULL,'192.168.1.115','U',''),
(7,110,'base-weixin-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /portal/**\r\n        - /ws/**\r\n        - /open/notify/**\r\n        - /open/auth/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_wx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.weixin.mp.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - wx_app\r\n      - wx_menu\r\n      - wx_user\r\n      - wx_auto_reply\r\n      - wx_msg\r\n      - wx_mass_msg\r\n  #数据权限配置\r\n  datascope:\r\n    mapperIds:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.selectPage\r\n\r\n# 微信第三方平台配置，请自行申请\r\nwx:\r\n  component:\r\n    appId: wxedb42aa502a8b83d\r\n    appSecret: a76dc60602a6783058bf1661433ebb28\r\n    token: gh_26fd6cdbd78b\r\n    aesKey: DYnwvIfD47b7QkIKrO6a3OKgI172VrRaXLil48JEjr0','7ecdeb77119c557e64f9fcdac2a6e3d9','2010-05-05 00:00:00','2019-09-03 12:45:57',NULL,'192.168.1.115','U',''),
(88,111,'base-weixin-ma-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: miniapp\r\n      client-secret: miniapp\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_wx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.weixin.ma.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - wx_app\r\n      - wx_user\r\n  #数据权限配置\r\n  datascope:\r\n    mapperIds:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.selectPage','8bc3811a0d23985cc126a0a1f422c6bc','2010-05-05 00:00:00','2019-09-03 12:48:09',NULL,'192.168.1.115','D',''),
(1,112,'dynamic_routes','DEFAULT_GROUP','','routes:\r\n# base-auth\r\n- id: base-auth\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /auth/**\r\n  filters:\r\n  - name: ValidateCodeGatewayFilter\r\n    args: {}\r\n  - name: PasswordDecoderFilter\r\n    args: {}\r\n  uri: lb://base-auth\r\n  order: 0\r\n# base-upms-admin\r\n- id: base-upms-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /admin/**\r\n  filters:\r\n  - name: RequestRateLimiter\r\n    args: \r\n      # 限流策略\r\n      key-resolver: \'#{@remoteAddrKeyResolver}\'\r\n      # 令牌桶每秒填充率\r\n      redis-rate-limiter.burstCapacity: 20\r\n      # 令牌桶容量\r\n      redis-rate-limiter.replenishRate: 10\r\n  # 熔断\r\n  - name: Hystrix\r\n    args: \r\n      fallbackUri: \'forward:/fallback\'\r\n      name: default\r\n  uri: lb://base-upms-admin\r\n  order: 0\r\n# base-codegen\r\n- id: base-codegen\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /gen/**\r\n  filters: []\r\n  uri: lb://base-codegen\r\n  order: 0\r\n# base-weixin-admin\r\n- id: base-weixin-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /weixin/**\r\n  filters: []\r\n  uri: lb://base-weixin-admin\r\n  order: 0\r\n# base-weixin-ma\r\n- id: base-weixin-ma\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /wxma/**\r\n  filters: []\r\n  uri: lb://base-weixin-ma\r\n  order: 0\r\n# base-mall-admin\r\n- id: base-mall-admin\r\n  predicates:\r\n  - name: Path\r\n    args: \r\n      _genkey_0: /mall/**\r\n  filters: []\r\n  uri: lb://base-mall-admin\r\n  order: 0','9bda4a838da7fd71263ca798bfcc55f5','2010-05-05 00:00:00','2019-09-03 12:51:07',NULL,'192.168.1.115','U',''),
(8,113,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart','8061a3915b3f8a0de0c0a86fe8c9992b','2010-05-05 00:00:00','2019-09-10 14:44:56',NULL,'192.168.1.115','U',''),
(8,114,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail','f5b5e243a426d5ba808fd2fd07daa411','2010-05-05 00:00:00','2019-09-10 15:28:16',NULL,'192.168.1.115','U',''),
(8,115,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail','7b9b61f01fbe9d01f20472b8c6dae3dc','2010-05-05 00:00:00','2019-09-11 14:27:51',NULL,'192.168.1.115','U',''),
(7,116,'base-weixin-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /portal/**\r\n        - /ws/**\r\n        - /open/notify/**\r\n        - /open/auth/**\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_wx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.weixin.mp.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - wx_app\r\n      - wx_menu\r\n      - wx_user\r\n      - wx_auto_reply\r\n      - wx_msg\r\n      - wx_mass_msg\r\n  #数据权限配置\r\n  datascope:\r\n    mapperIds:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.selectPage\r\n\r\n# 微信第三方平台配置，请自行申请\r\nwx:\r\n  component:\r\n    appId: wxedb42aa502a8b83d\r\n    appSecret: a76dc60602a6783058bf1661433ebb28\r\n    token: gh_26fd6cdbd78b\r\n    aesKey: DYnwvIfD47b7QkIKrO6a3OKgI172VrRaXLil48JEjr0','597959fad36daaaba74ba9cc12ab0850','2010-05-05 00:00:00','2019-09-11 16:24:17',NULL,'192.168.1.115','U',''),
(8,117,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address','5a37b7fd2aafe23697aa88fd8becf897','2010-05-05 00:00:00','2019-09-15 21:14:43',NULL,'192.168.31.203','U',''),
(8,118,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\nmybatis-plus:\r\n  # 配置扫描通用枚举 支持统配符 * 或者 ; 分割\r\n  typeEnumsPackage: com.joolun.cloud.mall.common.enums\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address','5d0ba735eb4190e1ca10d8447d9e18f5','2010-05-05 00:00:00','2019-09-15 21:23:17',NULL,'192.168.31.203','U',''),
(2,119,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','a3a49794095c761844dbf51a284980c2','2010-05-05 00:00:00','2019-09-15 21:24:15',NULL,'192.168.31.203','U',''),
(2,120,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  # 配置扫描通用枚举 支持统配符 * 或者 ; 分割\n  typeEnumsPackage: com.joolun.cloud.*.enums\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','78c3c81917feb59ed63a0fd43c7e14a0','2010-05-05 00:00:00','2019-09-15 21:33:25',NULL,'192.168.31.203','U',''),
(2,121,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  # 配置扫描通用枚举 支持统配符 * 或者 ; 分割\n  typeEnumsPackage: com.joolun.cloud.**.enums\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','fc1d7e46c531ff2d06f1d3efee1b7fbe','2010-05-05 00:00:00','2019-09-15 21:34:40',NULL,'192.168.31.203','U',''),
(2,122,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  # 配置扫描通用枚举 支持统配符 * 或者 ; 分割\n  typeEnumsPackage: com.joolun.cloud.*.*.enums\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','594f9bf5024afe5851970d3288309365','2010-05-05 00:00:00','2019-09-15 21:36:02',NULL,'192.168.31.203','U',''),
(2,123,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  # 配置扫描通用枚举 支持统配符 * 或者 ; 分割\n  typeEnumsPackage: com.joolun.cloud.*.enums\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','78c3c81917feb59ed63a0fd43c7e14a0','2010-05-05 00:00:00','2019-09-15 21:40:40',NULL,'192.168.31.203','U',''),
(2,124,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  # 配置扫描通用枚举 支持统配符 * 或者 ; 分割\n  typeEnumsPackage: com.joolun.cloud.**.enums\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','fc1d7e46c531ff2d06f1d3efee1b7fbe','2010-05-05 00:00:00','2019-09-18 10:38:16',NULL,'192.168.1.115','U',''),
(8,125,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address','5a37b7fd2aafe23697aa88fd8becf897','2010-05-05 00:00:00','2019-09-18 17:23:43',NULL,'192.168.1.115','U',''),
(8,126,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n  #商城相关配置\r\n  mall:\r\n    #支付回调地址\r\n    notify-url: http://gateway.joolun.com/','1c055b057bada270f1b8442312633c9b','2010-05-05 00:00:00','2019-09-18 17:28:11',NULL,'192.168.1.115','U',''),
(8,127,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n  #商城相关配置\r\n  mall:\r\n    #支付回调地址\r\n    notify-host: http://gateway.joolun.com','4717f590023fd2b6c08194abe7210f8e','2010-05-05 00:00:00','2019-09-18 17:34:11',NULL,'192.168.1.115','U',''),
(2,128,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    password: \n    host: ${REDIS-HOST:base-redis}\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','a3a49794095c761844dbf51a284980c2','2010-05-05 00:00:00','2019-09-19 09:36:32',NULL,'192.168.1.115','U',''),
(8,129,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n  #商城相关配置\r\n  mall:\r\n    #支付回调地址域名\r\n    notify-host: http://gateway.joolun.com','f8fe14b332ff89e6b8879aa81cb80276','2010-05-05 00:00:00','2019-09-20 17:28:02',NULL,'192.168.1.115','U',''),
(8,130,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n  #商城相关配置\r\n  mall:\r\n    #支付回调地址域名\r\n    notify-host: http://gateway.joolun.com\r\n    #快递100授权key\r\n    logistics-key: NXQCqRoe7950','95d72fb667094e7127a310064d87e37c','2010-05-05 00:00:00','2019-09-21 11:01:11',NULL,'192.168.31.203','U',''),
(8,131,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n  #商城相关配置\r\n  mall:\r\n    #支付、物流回调地址域名\r\n    notify-host: http://gateway.joolun.com\r\n    #快递100授权key\r\n    logistics-key: NXQCqRoe7950','a604ffdfc2b45b32bda7794341300461','2010-05-05 00:00:00','2019-09-22 20:44:44',NULL,'192.168.31.203','U',''),
(8,132,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n      - user_collect\r\n  #商城相关配置\r\n  mall:\r\n    #支付、物流回调地址域名\r\n    notify-host: http://gateway.joolun.com\r\n    #快递100授权key\r\n    logistics-key: NXQCqRoe7950','a1b9f619ef0e4ee474f39181337ac610','2010-05-05 00:00:00','2019-09-23 09:10:20',NULL,'192.168.1.115','U',''),
(2,133,'application-dev.yml','DEFAULT_GROUP','','# 加解密根密码\njasypt:\n  encryptor:\n    password: joolun #根密码\n# redis 相关\nspring:\n  redis:\n    host: ${REDIS-HOST:base-redis}\n    port: 6379\n    password: \n    database: 0\n# logging日志\nlogging:\n  level:\n    com.alibaba.nacos.client.naming: error\n# 暴露监控端点\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n\n# feign 配置\nfeign:\n  hystrix:\n    enabled: true\n  okhttp:\n    enabled: true\n  httpclient:\n    enabled: false\n  client:\n    config:\n      default:\n        connectTimeout: 10000\n        readTimeout: 10000\n  compression:\n    request:\n      enabled: true\n    response:\n      enabled: true\n# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s\n# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          strategy: SEMAPHORE\n          thread:\n            timeoutInMilliseconds: 60000\n  shareSecurityContext: true\n\n#请求处理的超时时间\nribbon:\n  ReadTimeout: 10000\n  ConnectTimeout: 10000\n\n# mybaits-plus配置\nmybatis-plus:\n  # MyBatis Mapper所对应的XML文件位置\n  mapper-locations: classpath:/mapper/*Mapper.xml\n  # 自定义TypeHandler\n  type-handlers-package: com.joolun.cloud.common.data.mybatis.typehandler\n  global-config:\n    sql-parser-cache: true\n    # 关闭MP3.0自带的banner\n    banner: false\n    db-config:\n      # 主键类型\n      id-type: auto\n\n#swagger公共信息\nswagger:\n  title: JooLun API\n  description: JooLun微信快速开发框架\n  license: Powered By joolun\n  licenseUrl: http://www.joolun.com/\n  terms-of-service-url: http://www.joolun.com/\n  authorization:\n    name: OAuth\n    auth-regex: ^.*$\n    authorization-scope-list:\n      - scope: server\n        description: server all\n    token-url-list:\n      - http://${GATEWAY-HOST:base-gateway}:${GATEWAY-PORT:9999}/auth/oauth/token\n\n## spring security 配置\nsecurity:\n  oauth2:\n    client:\n      # 无需token访问的url,如果子模块重写这里的配置就会被覆盖\n      release-urls:\n        - /actuator/**\n        - /v2/api-docs\n    resource:\n      loadBalanced: true\n      token-info-uri: http://${AUTH-HOST:base-auth}/oauth/check_token','ac85a0ba2f89889ead6e73c71873c60d','2010-05-05 00:00:00','2019-09-24 17:05:59',NULL,'192.168.1.115','U',''),
(8,134,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n      - user_collect\r\n      - goods_appraises\r\n  #商城相关配置\r\n  mall:\r\n    #支付、物流回调地址域名\r\n    notify-host: http://gateway.joolun.com\r\n    #快递100授权key\r\n    logistics-key: NXQCqRoe7950','3d14b0f4c1ace2862bb764a615ca5786','2010-05-05 00:00:00','2019-09-24 18:00:18',NULL,'192.168.1.115','U',''),
(8,135,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n      - user_collect\r\n      - goods_appraises\r\n  #商城相关配置\r\n  mall:\r\n    #支付、物流回调地址域名\r\n    notify-host: https://test-gateway.joolun.com\r\n    #快递100授权key\r\n    logistics-key: NXQCqRoe7950','08e18dadf1834de74e41b7014d69a356','2010-05-05 00:00:00','2019-09-25 21:15:02',NULL,'192.168.31.203','U',''),
(8,136,'base-mall-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_mall}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.mall.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - goods_category\r\n      - goods_spu\r\n      - goods_spu_spec\r\n      - goods_sku\r\n      - goods_sku_spec_value\r\n      - goods_spec\r\n      - goods_spec_value\r\n      - shopping_cart\r\n      - order_info\r\n      - order_item\r\n      - order_logistics\r\n      - order_logistics_detail\r\n      - user_address\r\n      - user_collect\r\n      - goods_appraises\r\n  #商城相关配置\r\n  mall:\r\n    #支付、物流回调地址域名\r\n    notify-host: https://gateway.joolun.com\r\n    #快递100授权key\r\n    logistics-key: NXQCqRoe7950','366b0a19ce059cecae49fe9ef96f1a7a','2010-05-05 00:00:00','2019-09-27 16:01:46',NULL,'192.168.1.115','U',''),
(7,137,'base-weixin-admin-dev.yml','DEFAULT_GROUP','','## spring security 配置\r\nsecurity:\r\n  oauth2:\r\n    client:\r\n      client-id: weixin\r\n      client-secret: weixin\r\n      scope: server\r\n      # 无需token访问的url\r\n      release-urls:\r\n        - /actuator/**\r\n        - /v2/api-docs\r\n        - /portal/**\r\n        - /ws/**\r\n        - /open/notify/**\r\n        - /open/auth/**\r\n        - /api/**\r\n# 数据源配置\r\nspring:\r\n  datasource:\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      username: ${MYSQL-USER:root}\r\n      password: ${MYSQL-PWD:root}\r\n      url: jdbc:mysql://${MYSQL-HOST:base-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:base_wx}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true\r\n  resources:\r\n    static-locations: classpath:/static/,classpath:/views/\r\n\r\n# Logger Config sql日志\r\nlogging:\r\n  level:\r\n    com.joolun.cloud.weixin.admin.mapper: debug\r\n    \r\n# 租户表维护\r\nbase:\r\n  tenant:\r\n    column: tenant_id\r\n    tables:\r\n      - wx_app\r\n      - wx_menu\r\n      - wx_user\r\n      - wx_auto_reply\r\n      - wx_msg\r\n      - wx_mass_msg\r\n  #数据权限配置\r\n  datascope:\r\n    mapperIds:\r\n      - com.joolun.cloud.weixin.mp.mapper.WxAppMapper.selectPage\r\n\r\n# 微信第三方平台配置，请自行申请\r\nwx:\r\n  component:\r\n    appId: wxedb42aa502a8b83d\r\n    appSecret: a76dc60602a6783058bf1661433ebb28\r\n    token: gh_26fd6cdbd78b\r\n    aesKey: DYnwvIfD47b7QkIKrO6a3OKgI172VrRaXLil48JEjr0','25710e4190c73db8ecbce11fc932a340','2010-05-05 00:00:00','2019-09-27 16:02:29',NULL,'192.168.1.115','U','');

/*Table structure for table `roles` */

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

/*Data for the table `roles` */

insert  into `roles`(`username`,`role`) values 
('nacos','ROLE_ADMIN');

/*Table structure for table `tenant_capacity` */

DROP TABLE IF EXISTS `tenant_capacity`;

CREATE TABLE `tenant_capacity` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '配额，0表示使用默认值',
  `usage` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '使用量',
  `max_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='租户容量信息表';

/*Data for the table `tenant_capacity` */

/*Table structure for table `tenant_info` */

DROP TABLE IF EXISTS `tenant_info`;

CREATE TABLE `tenant_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(20) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_tenant_info_kptenantid` (`kp`,`tenant_id`) USING BTREE,
  KEY `idx_tenant_id` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='tenant_info';

/*Data for the table `tenant_info` */

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

/*Data for the table `users` */

insert  into `users`(`username`,`password`,`enabled`) values 
('nacos','$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
